#!/bin/bash
#PBS -l nodes=1:ppn=12
#PBS -l walltime=1:00:00
#PBS -q batch
#PBS -N forest_fire
#PBS -j oe
#PBS -V

#cat $PBS_NODEFILE
cd ~/Final

mpiexec -np 1 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./main.cx
